### ISSUE TITLE
BlacklistedPerms doesn't work

### ISSUE THREAD

**Issue by Spinogl** [slvlr/PM2-Plugins#90]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: 1.8.8 paperspigot
 - Plugin Version: 3.9.37

**Describe the bug**
I've activated the "rewards don't repeat" function on my crate, but my players sometimes still get rewards they've already had.

**To Reproduce**
Take my crate file, the plugin, and try opening the crate several times. You'll see after 2 or 3 times that you'll get double rewards.

**Expected behavior**
When the "Rewards don't repeat" parameter is set to true, the same reward cannot be given twice.

**Config File**
https://pastebin.com/sy5scBEC

**Crate File**
https://pastebin.com/8z62qB20

**Comment by Spinogl** [comment]
Please fix this problem, it's particularly annoying for my server and for the players 🙏

**Comment by ThePM2** [comment]
Hey, sorry for the long wait, will try to have the fix issued in the next 24h

**Comment by Spinogl** [comment]
Thank you very much !

**Comment by Spinogl** [comment]
> Hey, sorry for the long wait, will try to have the fix issued in the next 24h

I'd like to take this opportunity to point out that the discord link in the advancedcrate update messages on spigot no longer works.

**Comment by ThePM2** [comment]
Wait I just checked your crate file and your size is set to 1. Maybe you misunderstood the configuration? Because how it's intended is that it doesn't give the same reward twice in the *SAME* crate opening. If you want to make it so the user doesn't get a particular reward ever, you would want to use BlacklistedPerms feature, and give a user a permission that would be defined in the configuration. It makes it so if a user has the specific permission he will not receive that reward ever. You can read more about it here
https://pm2plugins.gitbook.io/advancedcrates/general-information/rewards

**Comment by Spinogl** [comment]
Ohh, I'm so sorry, I didn't realise it was like that!
Thanks for the feedback, so I'll do that in my crates.
You've been a great help after all!

**Comment by Spinogl** [comment]
I'm going to reopen the ticket, as there is a bug with the BlacklistedPerms
On some animations, it doesn't work: see videos and crates config files

https://youtu.be/9SetP3eHniE
https://youtu.be/y2npx6vgje0
https://youtu.be/CJW6wXy8_BY

https://pastebin.com/Dj2YNBQn
https://pastebin.com/xA0MxxCe
https://pastebin.com/75yt4tSj
